Fixed broken file paths, VS link still broken due to multiple tag_invoke symbol definitions
atomgalaxy/zit pull request #2
Opened 2020-07-13 19:15 UTC by cppal

Note: Maybe the definitions in cars.hpp need to be made external and implemented in one of the cpp's?

2020-07-13 19:20 UTC, atomgalaxy requested changes
I don't particularly care about the vcproj stuff - I guess I could try and make sure that it works with visual studio. But this code *compiles* with VC++ on windows (with the cmake driver) so it's got to be a visual studio issue.

I don't think we need extern anything - the forward-declared-but-not-defined things are enough to make the linker link an external object, and we just link the two different implementations in. That's the way pimpl works, right?

2020-07-13 19:20 UTC, atomgalaxy commented on test/test_tag_invoke.cpp
> +#include "../taggie/tag_invoke.hpp"
same

2020-07-13 19:20 UTC, atomgalaxy commented on zit/zit.hpp
> +#include "../taggie/tag_invoke.hpp"
same, can't take this pull.

2020-07-13 19:20 UTC, atomgalaxy commented on cars/cars.hpp
> +#include "../zit/zit.hpp"
no, that's wrong. All file paths should be root-of-project-relative, not relative to the file.

2020-07-13 19:20 UTC, atomgalaxy commented on atomgalaxy.vcxproj.filters
> +    <ClCompile Include="test\test_tag_invoke.cpp">
Thanks, i hope this is correct now.

2020-07-13 19:20 UTC, atomgalaxy commented on atomgalaxy.vcxproj
> -    <ClCompile Include="zit\test\test_tag_invoke.cpp" />
Thanks, didn't check the visual studio vcxproj

2020-07-18 13:07 UTC, cppal commented
Please see my latest push to the VS branch. Still no luck though with the ADL errors, taking another look now.

2020-07-18 15:07 UTC, atomgalaxy approved these changes
LGTM, merging. Thanks so much! Currently I have no access to windows, but I'll try to open this with visual studio when I get may laptop back.

G

2020-07-19 13:06 UTC, merged